# Generated by Django 5.1.4 on 2025-09-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ridefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
