# Generated by Django 5.2.6 on 2025-09-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_ride_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=10),
        ),
    ]
